language: node_js

node_js:
  - "13"

script:
  - npm install coveralls --save-dev
  - npm run build
  - jest --coverage --coverageReporters=text-lcov | coveralls

cache:
  directories:
    - node_modules
